# Generated by Django 6.0.6 on 2026-06-20 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Watchlist', '0006_watchlist_avg_rating_watchlist_number_of_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='number_of_rating',
            new_name='number_of_reviews',
        ),
    ]
